name: XSX.Util

on: 
  push:
    tags: v*
  workflow_dispatch: # 手动触发

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Test
      run: dotnet test --configuration Release
  
  build:
    needs: test
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build --configuration Release
  
  publish:
    needs: [test, build]
    name: Publish Project to Nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Publish
      run: |       
        version=`git describe --tags`
        dotnet build --configuration Release
        dotnet pack XSX.Util.Extension --configuration release -p:PackageVersion=$version
        dotnet nuget push XSX.Util.Extension/bin/release/XSX.Util.Extension.*.nupkg -k ${APIKEY} -s https://api.nuget.org/v3/index.json

        dotnet pack XSX.Util.Helper --configuration release -p:PackageVersion=$version
        dotnet nuget push XSX.Util.Helper/bin/release/XSX.Util.Helper.*.nupkg -k ${APIKEY} -s https://api.nuget.org/v3/index.json

        dotnet pack XSX.Util.TestBase --configuration release -p:PackageVersion=$version
        dotnet nuget push XSX.Util.TestBase/bin/release/XSX.Util.TestBase.*.nupkg -k ${APIKEY} -s https://api.nuget.org/v3/index.json
      env:
        APIKEY: ${{ secrets.nuget_XSX_Util }}
