name: XSX.Util

on: 
  create:
  workflow_dispatch: # 手动触发

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        dotnet-version: [ '3.1.x' ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Test
      run: dotnet test --configuration Release
  
  build:
    needs: test
    name: Build Project
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        dotnet-version: [ '3.1.x' ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Build
      run: dotnet build --configuration Release
  
  publish:
    needs: [test, build]
    name: Publish Project to Nuget
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        dotnet-version: [ '3.1.x' ]
    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Publish
      run: |       
        version=`git describe --tags`
        dotnet build --configuration Release
        dotnet pack XSX.Util --configuration release -p:PackageVersion=$version 
        dotnet nuget push XSX.Util/bin/release/XSX.Util.*.nupkg -k ${APIKEY} -s https://api.nuget.org/v3/index.json

        dotnet pack XSX.Util.TestBase --configuration release -p:PackageVersion=$version 
        dotnet nuget push XSX.Util.TestBase/bin/release/XSX.Util.TestBase.*.nupkg -k ${APIKEY} -s https://api.nuget.org/v3/index.json

      env:
        APIKEY: ${{ secrets.nuget_XSX_Util }}
